micronaut:
  server:
    port: 8080
  application:
    name: micronaut-pract
netty:
  default:
    allocator:
      max-order: 3

jackson:
  serializationInclusion: ALWAYS
  date-format: 'YYYY-MM-DD'

customdatabase:
  host: "jdbc:postgresql://192.168.0.4:5432/examen"
  user: "postgres"
  password: "1234"
