/*
 * This file is generated by jOOQ.
 */
package schemas.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employess implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer   id;
    private final Integer   genderId;
    private final Integer   jobId;
    private final String    name;
    private final String    lastName;
    private final LocalDate birthdate;

    public Employess(Employess value) {
        this.id = value.id;
        this.genderId = value.genderId;
        this.jobId = value.jobId;
        this.name = value.name;
        this.lastName = value.lastName;
        this.birthdate = value.birthdate;
    }

    public Employess(
        Integer   id,
        Integer   genderId,
        Integer   jobId,
        String    name,
        String    lastName,
        LocalDate birthdate
    ) {
        this.id = id;
        this.genderId = genderId;
        this.jobId = jobId;
        this.name = name;
        this.lastName = lastName;
        this.birthdate = birthdate;
    }

    /**
     * Getter for <code>public.employess.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.employess.gender_id</code>.
     */
    public Integer getGenderId() {
        return this.genderId;
    }

    /**
     * Getter for <code>public.employess.job_id</code>.
     */
    public Integer getJobId() {
        return this.jobId;
    }

    /**
     * Getter for <code>public.employess.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.employess.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>public.employess.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employess (");

        sb.append(id);
        sb.append(", ").append(genderId);
        sb.append(", ").append(jobId);
        sb.append(", ").append(name);
        sb.append(", ").append(lastName);
        sb.append(", ").append(birthdate);

        sb.append(")");
        return sb.toString();
    }
}
