/*
 * This file is generated by jOOQ.
 */
package schemas.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jobs implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer    id;
    private final String     name;
    private final BigDecimal salary;

    public Jobs(Jobs value) {
        this.id = value.id;
        this.name = value.name;
        this.salary = value.salary;
    }

    public Jobs(
        Integer    id,
        String     name,
        BigDecimal salary
    ) {
        this.id = id;
        this.name = name;
        this.salary = salary;
    }

    /**
     * Getter for <code>public.jobs.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.jobs.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.jobs.salary</code>.
     */
    public BigDecimal getSalary() {
        return this.salary;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Jobs (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }
}
