version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://192.168.0.4:5432/examen
      JDBC_USER: postgres
      JDBC_PASSWORD: 1234
    depends_on:
      - db
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: examen