/*
 * This file is generated by jOOQ.
 */
package schemas.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.tables.Employess;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployessRecord extends UpdatableRecordImpl<EmployessRecord> implements Record6<Integer, Integer, Integer, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employess.id</code>.
     */
    public EmployessRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employess.gender_id</code>.
     */
    public EmployessRecord setGenderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.gender_id</code>.
     */
    public Integer getGenderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.employess.job_id</code>.
     */
    public EmployessRecord setJobId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.job_id</code>.
     */
    public Integer getJobId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.employess.name</code>.
     */
    public EmployessRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.employess.last_name</code>.
     */
    public EmployessRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.employess.birthdate</code>.
     */
    public EmployessRecord setBirthdate(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.employess.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return (LocalDate) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, String, LocalDate> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, String, String, LocalDate> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employess.EMPLOYESS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Employess.EMPLOYESS.GENDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Employess.EMPLOYESS.JOB_ID;
    }

    @Override
    public Field<String> field4() {
        return Employess.EMPLOYESS.NAME;
    }

    @Override
    public Field<String> field5() {
        return Employess.EMPLOYESS.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field6() {
        return Employess.EMPLOYESS.BIRTHDATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGenderId();
    }

    @Override
    public Integer component3() {
        return getJobId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public LocalDate component6() {
        return getBirthdate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGenderId();
    }

    @Override
    public Integer value3() {
        return getJobId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public LocalDate value6() {
        return getBirthdate();
    }

    @Override
    public EmployessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EmployessRecord value2(Integer value) {
        setGenderId(value);
        return this;
    }

    @Override
    public EmployessRecord value3(Integer value) {
        setJobId(value);
        return this;
    }

    @Override
    public EmployessRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployessRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public EmployessRecord value6(LocalDate value) {
        setBirthdate(value);
        return this;
    }

    @Override
    public EmployessRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDate value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployessRecord
     */
    public EmployessRecord() {
        super(Employess.EMPLOYESS);
    }

    /**
     * Create a detached, initialised EmployessRecord
     */
    public EmployessRecord(Integer id, Integer genderId, Integer jobId, String name, String lastName, LocalDate birthdate) {
        super(Employess.EMPLOYESS);

        setId(id);
        setGenderId(genderId);
        setJobId(jobId);
        setName(name);
        setLastName(lastName);
        setBirthdate(birthdate);
    }

    /**
     * Create a detached, initialised EmployessRecord
     */
    public EmployessRecord(schemas.tables.pojos.Employess value) {
        super(Employess.EMPLOYESS);

        if (value != null) {
            setId(value.getId());
            setGenderId(value.getGenderId());
            setJobId(value.getJobId());
            setName(value.getName());
            setLastName(value.getLastName());
            setBirthdate(value.getBirthdate());
        }
    }
}
