/*
 * This file is generated by jOOQ.
 */
package schemas.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import schemas.tables.Genders;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GendersRecord extends UpdatableRecordImpl<GendersRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.genders.id</code>.
     */
    public GendersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.genders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.genders.name</code>.
     */
    public GendersRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.genders.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Genders.GENDERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Genders.GENDERS.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public GendersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GendersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GendersRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GendersRecord
     */
    public GendersRecord() {
        super(Genders.GENDERS);
    }

    /**
     * Create a detached, initialised GendersRecord
     */
    public GendersRecord(Integer id, String name) {
        super(Genders.GENDERS);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised GendersRecord
     */
    public GendersRecord(schemas.tables.pojos.Genders value) {
        super(Genders.GENDERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
