/*
 * This file is generated by jOOQ.
 */
package schemas;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import schemas.tables.Employess;
import schemas.tables.EmployessWorked;
import schemas.tables.FlywaySchemaHistory;
import schemas.tables.Genders;
import schemas.tables.Jobs;
import schemas.tables.records.EmployessRecord;
import schemas.tables.records.EmployessWorkedRecord;
import schemas.tables.records.FlywaySchemaHistoryRecord;
import schemas.tables.records.GendersRecord;
import schemas.tables.records.JobsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployessRecord> EMPLOYESS_PKEY = Internal.createUniqueKey(Employess.EMPLOYESS, DSL.name("employess_pkey"), new TableField[] { Employess.EMPLOYESS.ID }, true);
    public static final UniqueKey<EmployessWorkedRecord> EMPLOYESS_WORKED_PKEY = Internal.createUniqueKey(EmployessWorked.EMPLOYESS_WORKED, DSL.name("employess_worked_pkey"), new TableField[] { EmployessWorked.EMPLOYESS_WORKED.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<GendersRecord> GENDERS_PKEY = Internal.createUniqueKey(Genders.GENDERS, DSL.name("genders_pkey"), new TableField[] { Genders.GENDERS.ID }, true);
    public static final UniqueKey<JobsRecord> JOBS_PKEY = Internal.createUniqueKey(Jobs.JOBS, DSL.name("jobs_pkey"), new TableField[] { Jobs.JOBS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployessRecord, GendersRecord> EMPLOYESS__FK_EMP_GEND = Internal.createForeignKey(Employess.EMPLOYESS, DSL.name("fk_emp_gend"), new TableField[] { Employess.EMPLOYESS.GENDER_ID }, Keys.GENDERS_PKEY, new TableField[] { Genders.GENDERS.ID }, true);
    public static final ForeignKey<EmployessRecord, JobsRecord> EMPLOYESS__FK_EMP_JOB = Internal.createForeignKey(Employess.EMPLOYESS, DSL.name("fk_emp_job"), new TableField[] { Employess.EMPLOYESS.JOB_ID }, Keys.JOBS_PKEY, new TableField[] { Jobs.JOBS.ID }, true);
    public static final ForeignKey<EmployessWorkedRecord, EmployessRecord> EMPLOYESS_WORKED__FK_WORKER_EMP = Internal.createForeignKey(EmployessWorked.EMPLOYESS_WORKED, DSL.name("fk_worker_emp"), new TableField[] { EmployessWorked.EMPLOYESS_WORKED.EMPLOYEE_ID }, Keys.EMPLOYESS_PKEY, new TableField[] { Employess.EMPLOYESS.ID }, true);
}
