/*
 * This file is generated by jOOQ.
 */
package schemas;


import schemas.tables.Employess;
import schemas.tables.EmployessWorked;
import schemas.tables.FlywaySchemaHistory;
import schemas.tables.Genders;
import schemas.tables.Jobs;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.employess</code>.
     */
    public static final Employess EMPLOYESS = Employess.EMPLOYESS;

    /**
     * The table <code>public.employess_worked</code>.
     */
    public static final EmployessWorked EMPLOYESS_WORKED = EmployessWorked.EMPLOYESS_WORKED;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.genders</code>.
     */
    public static final Genders GENDERS = Genders.GENDERS;

    /**
     * The table <code>public.jobs</code>.
     */
    public static final Jobs JOBS = Jobs.JOBS;
}
